In [ ]:
import numpy as np

In [ ]:
import sklearn
from sklearn.metrics import hamming_loss, f1_score, precision_score, recall_score

In [ ]:
true = np.array([[1,0,1,0], [0,1,0,1], [1,0,0,1],[0,1,1,0],[1,0,0,0]])

In [ ]:
true

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 0]])

In [ ]:
predicted = np.array([[1,0,0,1],[0,1,1,1],[1,0,0,1],[0,1,0,0],[1,0,0,1]])

In [ ]:
predicted

array([[1, 0, 0, 1],
       [0, 1, 1, 1],
       [1, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 1]])

In [ ]:
hamming_loss(true,predicted)

0.25

In [ ]:
precision_score(true,predicted,average='micro')

0.7

In [ ]:
recall_score(true,predicted,average='micro')

0.7777777777777778

In [ ]:
display(true)

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 0]])